### ISSUE TITLE
2017.1.4 RWD fab button hyperlink bug

### ISSUE THREAD

**Issue by HsuKaoPang** [ludonow/ludo-beta-react#1]
![image](https://cloud.githubusercontent.com/assets/15105232/21615093/fd9ea538-d216-11e6-8982-79dacb1c229a.png)
![image](https://cloud.githubusercontent.com/assets/15105232/21615152/2fb9234a-d217-11e6-9d84-17f2fe0940a5.png)

1. If statement of login/logout hyperlink
2. profile
3. tamplate

**Comment by Sirius207** [comment]
Fix it
