### ISSUE TITLE
手機版回報頁面無法上傳圖片

### ISSUE THREAD

**Issue by sean820117** [ludonow/ludo-beta-react#10]

**Comment by YongYuH** [comment]
推測是因為上傳圖片容量太大，但是沒有跳出錯誤訊息，所以使用者認為是圖片上傳功能異常。

**Comment by Sirius207** [comment]
我這裡沒有圖片的log，覺得需要要一下照片 囧

**Comment by YongYuH** [comment]
手機板 safari 瀏覽器上傳圖片有 bug

**Comment by YongYuH** [comment]
手機版回報圖片上傳最大容量先改為 1MB
因為 s3 資料庫設定預設為圖片大小超過 1MB 無法儲存
https://github.com/ludonow/ludo-beta-react/commit/c8295b2079b8a23e8256f0c3e2726b91766e0598
