### ISSUE TITLE
[修正] 無限捲動 Bad Request

### ISSUE THREAD

**Issue by Sirius207** [ludonow/ludo-beta-react#2]
注意卡片數量沒有超過25 張時後端不會回傳 startkey 
如果有超過再run無限捲動
![image](https://cloud.githubusercontent.com/assets/7900936/25649177/c9659b6c-3005-11e7-89d7-d70420208c12.png)

**Comment by YongYuH** [comment]
fixed in https://github.com/ludonow/ludo-beta-react/commit/4efa32c52fea484b85490970cfd4d51a226ef519
