### ISSUE TITLE
[調整]  回報輸入區

### ISSUE THREAD

**Issue by Sirius207** [ludonow/ludo-beta-react#3]
沒有登入時不應該可以在留言區輸入(雖然不會真的送出)

期待
點擊輸入框，輸入時會跳轉到登入頁面

現狀
![image](https://cloud.githubusercontent.com/assets/7900936/25980561/efa0b67e-3701-11e7-8c4b-c33d4c96e1a0.png)

**Comment by YongYuH** [comment]
bug fixed in https://github.com/ludonow/ludo-beta-react/commit/110565e7c22c27132d27c70568d89b7f331d30ce
