### ISSUE TITLE
[修正]  刪除留言問題

### ISSUE THREAD

**Issue by Sirius207** [ludonow/ludo-beta-react#4]
刪除留言後，若輸入新的回報，新回報的留言串會是顯示剛剛刪除的留言那串。

期待
新的回報底下不要有舊的留言文字

現況
會出現剛剛刪除的留言文字（重整會不見）

**Comment by YongYuH** [comment]
fixed in https://github.com/ludonow/ludo-beta-react/commit/1ce8d8d9edc0f9b35686c83cd9be89f480fd657f
