### ISSUE TITLE
顯示已經結束Ludo的頁面

### ISSUE THREAD

**Issue by Sirius207** [ludonow/ludo-beta-react#60]

**Comment by YongYuH** [comment]
demo 用，filter 按鈕暫時先放 head bar
https://github.com/ludonow/ludo-beta-react/commit/0bb203ffed7ee062d5273e81a79ec8f1472a9a91

**Comment by YongYuH** [comment]
手機板已放入 toggle bar menu
https://github.com/ludonow/ludo-beta-react/commit/47b19145f669f17a5f215cf68eff9295784d4fc9
