### ISSUE TITLE
Go 連結疑問

### ISSUE THREAD

**Issue by Sirius207** [ludonow/ludo-beta-react#63]
可能需求：
需要一次看很多張卡片時，使用者可能會想用右鍵一次開啟多張卡片查看內容

目前狀況：
Go右鍵點擊後無法使用再新分頁開啟連結這選項，因為不是連結

疑問：
這裡調整成連結會很花時間嗎？~

![image](https://user-images.githubusercontent.com/7900936/29804088-bba098a6-8cb2-11e7-96c2-cdc9689b4d86.png)

**Comment by YongYuH** [comment]
之前是因為點擊 GO 的瞬間才能確定要連去哪一個 ludo_id，所以才用 click event 來 routing。不過應該是可以 a tag 直接跟 ludo card list 的 id 合起來，這個要想一下怎麼做，會花一些時間。

**Comment by YongYuH** [comment]
好像比我想像中簡單，已經改完了。
https://github.com/ludonow/ludo-beta-react/commit/9d27c7620bc822baf63fa80511ed4e6e8b2d295d

**Comment by Sirius207** [comment]
讚讚
