### ISSUE TITLE
已結束的卡片回報功能應關閉

### ISSUE THREAD

**Issue by YongYuH** [ludonow/ludo-beta-react#66]
已結束的卡片仍然可以成功送出回報

**Comment by Sirius207** [comment]
後端已擋，將回傳以下內容
`{
   'status': '400',
   'message': 'can not report end card!'
    }`

**Comment by YongYuH** [comment]
移除電腦版回報按鈕
https://github.com/ludonow/ludo-beta-react/commit/a1e16a0f1b7a33e74acf40101662140b19be66d2

移除手機版回報按鈕
https://github.com/ludonow/ludo-beta-react/commit/478884c88d6f0c5e08b1908b6252ea84315db8c4
