### ISSUE TITLE
回報未依時間順序排列

### ISSUE THREAD

**Issue by YongYuH** [ludonow/ludo-beta-react#75]
![default](https://user-images.githubusercontent.com/10210800/36214092-80963430-11e3-11e8-9fba-70a86a31516e.JPG)

**Comment by Sirius207** [comment]
這我也看一下，如果是同一天的兩個回報的確舊的會在上面

**Comment by YongYuH** [comment]
按照時間降冪排列回報
https://github.com/ludonow/ludo-beta-react/commit/e3ce7b7d9d8906199808f1afe61cf038c379b475
