### ISSUE TITLE
載入中New Button 上方出現文字

### ISSUE THREAD

**Issue by Sirius207** [ludonow/ludo-beta-react#77]

**Comment by YongYuH** [comment]
卡片列表與我的卡片列表新增載入中動畫
https://github.com/ludonow/ludo-beta-react/commit/369d2e45960227677ad5325d44f0970b36213fd8

個人卡片列表(卡片列表上方部分)新增載入動畫
https://github.com/ludonow/ludo-beta-react/commit/90ddd242a8f1b38843011d0cac7e7537136e74a8
